package models

import "time"

// ─────────────────────────────────────────────────────────────────────────
// Module 1: Authentication System  +  Module 2: RBAC System
//
// Supabase integration point (Step 1 requirement):
// Supabase Auth owns the `auth.users` table (email, password hash, OAuth
// identities, email confirmation, etc.) in a schema this backend never
// migrates or writes to directly. `Profile` is the `public` schema
// counterpart: one row per `auth.users` row, holding only the
// application-specific fields this project needs (role, display name,
// status, ...). Profile.ID is NOT auto-generated by GORM — it is always
// set to the same UUID as the corresponding auth.users.id.
//
// The row is created either by:
//   (a) a Postgres trigger on auth.users (`on_auth_user_created`) that
//       INSERTs into public.profiles, or
//   (b) the Go backend, right after it verifies a brand-new Supabase JWT
//       for a user that has no Profile row yet (created lazily on first
//       authenticated request).
// Either way, the Go backend never issues or verifies passwords itself —
// it only verifies the Supabase-issued JWT (see Step 3: JWT middleware)
// and trusts the `sub` claim as the Profile ID.
// ─────────────────────────────────────────────────────────────────────────

// Profile is the public-schema profile row for a Supabase Auth user.
// 1 Role -> many Profiles (a Role "has many" Profiles).
type Profile struct {
	ID              string     `gorm:"type:uuid;primaryKey" json:"id"` // == auth.users.id, not auto-generated here
	RoleID          *string    `gorm:"type:uuid;index" json:"role_id"`
	Role            *Role      `gorm:"foreignKey:RoleID" json:"role,omitempty"`
	Name            string     `gorm:"size:150;not null" json:"name"`
	Gender          string     `gorm:"size:20" json:"gender"`
	PhoneNumber     string     `gorm:"size:30" json:"phone_number"`
	ProfileImageURL string     `json:"profile_image_url"`
	Status          string     `gorm:"size:20;default:'active'" json:"status"` // active | suspended
	LastLoginAt     *time.Time `json:"last_login_at"`
	CreatedAt       time.Time  `json:"created_at"`
	UpdatedAt       time.Time  `json:"updated_at"`
}

// Role: 1 Role has many Profiles.
type Role struct {
	ID       string    `gorm:"type:uuid;primaryKey;default:gen_random_uuid()" json:"id"`
	RoleName string    `gorm:"size:50;uniqueIndex;not null" json:"role_name"` // Admin, Organizer, TeamManager, Player, Referee, ...
	Profiles []Profile `gorm:"foreignKey:RoleID" json:"-"`
}

// Permission: 1 Role has many Permissions, one row per module the role can touch.
type Permission struct {
	ID        string `gorm:"type:uuid;primaryKey;default:gen_random_uuid()" json:"id"`
	RoleID    string `gorm:"type:uuid;not null;index" json:"role_id"`
	Role      Role   `gorm:"foreignKey:RoleID" json:"-"`
	Module    string `gorm:"size:100;not null" json:"module"` // e.g. "team", "tournament", "prize"
	CanView   bool   `json:"can_view"`
	CanCreate bool   `json:"can_create"`
	CanEdit   bool   `json:"can_edit"`
	CanDelete bool   `json:"can_delete"`
}

// Session is an app-level login-activity record. Supabase Auth already
// issues and manages the real JWT/session lifecycle; this table exists
// only so the AdminEye/AuditLog side of RBAC has something to query
// (idle/absolute timeout bookkeeping, "active sessions" admin view, etc.).
type Session struct {
	ID        string    `gorm:"type:uuid;primaryKey;default:gen_random_uuid()" json:"id"`
	ProfileID string    `gorm:"type:uuid;not null;index" json:"profile_id"`
	Profile   Profile   `gorm:"foreignKey:ProfileID" json:"-"`
	CreatedAt time.Time `json:"created_at"`
	ExpiresAt time.Time `json:"expires_at"`
	IsActive  bool      `gorm:"default:true" json:"is_active"`
}

// AuditLog records system-wide security-relevant events (login, suspend, etc).
type AuditLog struct {
	ID                string    `gorm:"type:uuid;primaryKey;default:gen_random_uuid()" json:"id"`
	ActorName         string    `gorm:"size:150" json:"actor_name"` // Profile name, or "System"
	ActionType        string    `gorm:"size:100" json:"action_type"`
	TargetDescription string    `json:"target_description"`
	Timestamp         time.Time `json:"timestamp"`
}
